production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: ddn4hmo78mjaos
  pool: 5
  username: njeerekkvjqqkn
  password: ZjFXLB-TVeyjEEG0MoCPVLJQmp
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dance_dev
  pool: 5
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_test
  pool: 5
  username: root
  password:
          Couldn't create database for {"adapter"=>"postgresql", "username"=>"njeerekkvjqqkn", "password"=>"ZjFXLB-TVeyjEEG0MoCPVLJQmp", "port"=>5432, "database"=>"ddn4hmo78mjaos", "host"=>"ec2-50-17-181-147.compute-1.amazonaws.com"}

