production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: ddn4hmo78mjaos
  pool: 5
  username: njeerekkvjqqkn
  password: ZjFXLB-TVeyjEEG0MoCPVLJQmp
  host: ec2-50-17-181-147.compute-1.amazonaws.com
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dance
  pool: 5
  username: root
  password: hakvng2015
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_test
  pool: 5
  username: root
  password:
